Clarified configuration warning on doc building
git-svn-id: svn+ssh://svn.code.sf.net/p/check/code/trunk@115 64e312b2-a51f-0410-8e61-82d0ca0eb02a

diff --git a/check/configure b/check/configure
--- a/check/configure
+++ b/check/configure
@@ -1227,7 +1227,7 @@ else
 fi
 
 if test x"$have_sgmltools" != "xyes" -o x"$have_lyx" != "xyes" ; then
-	echo "configure: warning: couldn't find sgml2html, not building docs" 1>&2
+	echo "configure: warning: required tools not found, not building docs" 1>&2
 fi
 
 
