Hopefully automake releases.
git-svn-id: svn+ssh://svn.code.sf.net/p/check/code/trunk@548 64e312b2-a51f-0410-8e61-82d0ca0eb02a

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -38,3 +38,75 @@ SVNChangeLog:
 	fi
 
 ACLOCAL_AMFLAGS = -I m4
+
+doc/check.html:
+	$(MAKE) -C doc check.html
+
+# check we can do a clean build, including docs.
+# perhaps we should check for out of date (svn st -u) and modified files.
+prereleasecheck: doc/check.html
+	-$(MAKE) distclean
+	./autoreconf -i && ./configure \
+	    && ulimit -c 0 && \
+	    $(MAKE) distcheck
+
+RELEASE_VERSION ?= unset
+SF_USERNAME ?= unset
+SVN_REVNO = `svn st -u | grep "Status against revision:" | awk '{ print $4 }'`
+releasevars:
+	@if [ "unset" = "${RELEASE_VERSION}" ]; then \
+	    echo "set RELEASE_VERSION to something like 0.9.6 to prepare a release."; \
+	    false; \
+	fi
+	@if [ "unset" = "${SF_USERNAME}" ]; then \
+	    echo "set SF_USERNAME to your sourceforge username"; \
+	    false; \
+	fi
+
+preparerelease: releasevars prereleasecheck
+	-# check we have can connect properly to do release tasks before tagging:
+	sftp -b /dev/null ${SF_USERNAME}@web.sourceforge.net
+	sftp -b /dev/null ${SF_USERNAME}@frs.sourceforge.net
+	svn cp -rXXX https://svn.sourceforge.net/svnroot/check/trunk https://svn.sourceforge.net/svnroot/check/tags/check-${RELEASE_VERSION}
+	svn co https://svn.sourceforge.net/svnroot/check/tags/check-${RELEASE_VERSION} check-${RELEASE_VERSION}
+	@echo "You need to:"
+	@echo "Update NEWS with info from `svn log | less`."
+	@echo "Update TODO and make sure version numbers match appropriately."
+	@echo "Update configure.ac with new version numbers."
+	@echo "Then svn commit these changes."
+	@echo "CTRL-D when finished or 'exit 1' to abort."
+	@echo "aborting will leave the partially prepared release in" `pwd`
+	cd check-${RELEASE_VERSION} && ${SHELL} 
+	$(MAKE) -C check-${RELEASE_VERSION} dorelease
+	-svn merge -r${SVN_REVNO}:`svn st -u check-${RELEASE_VERSION} | grep "Status against revision:" | awk '{ print $4 }'` ../tags/check-${RELEASE_VERSION} .
+	@echo "Please resolve any conflicts"
+	${SHELL}
+	svn ci -m "Merge back release ${RELEASE_VERSION}"
+
+
+dorelease: releasevars doc/check.html prereleasecheck
+	cp NEWS NEWS-${RELEASE_VERSION}.txt
+	@echo "You need to:"
+	@echo "cut out old release news from NEWS-${RELEASE_VERSION}.txt."
+	@echo "Add anything important from SVNChangeLog to NEWS-release."
+	@echo "CTRL-D to complete, or exit 1 to abort."
+	${SHELL}
+	@echo uploading...
+	rsync -e ssh NEWS-${RELEASE_VERSION}.txt ${SF_USERNAME},check@frs.sourceforge.net:/home/frs/project/c/ch/check/check/${RELEASE_VERSION}/
+	rsync -e ssh check-${RELEASE_VERSION}.tar.gz ${SF_USERNAME},check@frs.sourceforge.net:/home/frs/project/c/ch/check/check/${RELEASE_VERSION}/
+	rsync -av doc/. ${SF_USERNAME},check@web.sourceforge.net:/home/groups/c/ch/check/htdocs
+	@echo "visit https://sourceforge.net/project/admin/explorer.php?group_id=28255"
+	@echo "Mark the NEWS file in check/${RELEASE_VERSION} as being a release note."
+	@echo "And the tar.gz file as being 'all platforms', using the NEWS file for release notes."
+	@echo "visit https://sourceforge.net/projects/check/files/"
+	@echo "Check it looks ok. It may take 15 minutes to show up."
+	@echo Finally, mail check-devel ,announce and users at lists dot sourceforge dot net
+	@echo an email (template is in HACKING) about this announcement.
+	@echo NEWS-release can be found at `pwd`/NEWS-release
+	@echo Note that with the tarballs, docs amd NEWS up, the release is done :P
+	@echo so you'll have to manuall roll back if you abort.
+	@echo "CTRL-D to complete, or exit 1 to abort."
+	${SHELL}
+	
+
+.PHONY: releasevars prereleasecheck preparerelease dorelease
